#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PlacementApp.Droid.Resource", IsApplication=true)]

namespace PlacementApp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F070006
			public const int abc_ab_share_pack_mtrl_alpha = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int abc_action_bar_item_background_material = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int abc_btn_borderless_material = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int abc_btn_check_material = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int abc_btn_check_to_on_mtrl_000 = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int abc_btn_check_to_on_mtrl_015 = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int abc_btn_colored_material = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int abc_btn_default_mtrl_shape = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int abc_btn_radio_material = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int abc_btn_radio_to_on_mtrl_000 = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int abc_btn_radio_to_on_mtrl_015 = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int abc_btn_switch_to_on_mtrl_00001 = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int abc_btn_switch_to_on_mtrl_00012 = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int abc_cab_background_internal_bg = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int abc_cab_background_top_material = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int abc_cab_background_top_mtrl_alpha = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int abc_control_background_material = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int abc_dialog_material_background = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int abc_edit_text_material = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int abc_ic_ab_back_material = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int abc_ic_arrow_drop_right_black_24dp = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int abc_ic_clear_material = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int abc_ic_commit_search_api_mtrl_alpha = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int abc_ic_go_search_api_material = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int abc_ic_menu_copy_mtrl_am_alpha = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int abc_ic_menu_cut_mtrl_alpha = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int abc_ic_menu_overflow_material = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int abc_ic_menu_paste_mtrl_am_alpha = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int abc_ic_menu_selectall_mtrl_alpha = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int abc_ic_menu_share_mtrl_alpha = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int abc_ic_search_api_material = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int abc_ic_star_black_16dp = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int abc_ic_star_black_36dp = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int abc_ic_star_black_48dp = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int abc_ic_star_half_black_16dp = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int abc_ic_star_half_black_36dp = 2131165225;
			
			// aapt resource value: 0x7F07002A
			public const int abc_ic_star_half_black_48dp = 2131165226;
			
			// aapt resource value: 0x7F07002B
			public const int abc_ic_voice_search_api_material = 2131165227;
			
			// aapt resource value: 0x7F07002C
			public const int abc_item_background_holo_dark = 2131165228;
			
			// aapt resource value: 0x7F07002D
			public const int abc_item_background_holo_light = 2131165229;
			
			// aapt resource value: 0x7F07002E
			public const int abc_list_divider_material = 2131165230;
			
			// aapt resource value: 0x7F07002F
			public const int abc_list_divider_mtrl_alpha = 2131165231;
			
			// aapt resource value: 0x7F070030
			public const int abc_list_focused_holo = 2131165232;
			
			// aapt resource value: 0x7F070031
			public const int abc_list_longpressed_holo = 2131165233;
			
			// aapt resource value: 0x7F070032
			public const int abc_list_pressed_holo_dark = 2131165234;
			
			// aapt resource value: 0x7F070033
			public const int abc_list_pressed_holo_light = 2131165235;
			
			// aapt resource value: 0x7F070034
			public const int abc_list_selector_background_transition_holo_dark = 2131165236;
			
			// aapt resource value: 0x7F070035
			public const int abc_list_selector_background_transition_holo_light = 2131165237;
			
			// aapt resource value: 0x7F070036
			public const int abc_list_selector_disabled_holo_dark = 2131165238;
			
			// aapt resource value: 0x7F070037
			public const int abc_list_selector_disabled_holo_light = 2131165239;
			
			// aapt resource value: 0x7F070038
			public const int abc_list_selector_holo_dark = 2131165240;
			
			// aapt resource value: 0x7F070039
			public const int abc_list_selector_holo_light = 2131165241;
			
			// aapt resource value: 0x7F07003A
			public const int abc_menu_hardkey_panel_mtrl_mult = 2131165242;
			
			// aapt resource value: 0x7F07003B
			public const int abc_popup_background_mtrl_mult = 2131165243;
			
			// aapt resource value: 0x7F07003C
			public const int abc_ratingbar_indicator_material = 2131165244;
			
			// aapt resource value: 0x7F07003D
			public const int abc_ratingbar_material = 2131165245;
			
			// aapt resource value: 0x7F07003E
			public const int abc_ratingbar_small_material = 2131165246;
			
			// aapt resource value: 0x7F07003F
			public const int abc_scrubber_control_off_mtrl_alpha = 2131165247;
			
			// aapt resource value: 0x7F070040
			public const int abc_scrubber_control_to_pressed_mtrl_000 = 2131165248;
			
			// aapt resource value: 0x7F070041
			public const int abc_scrubber_control_to_pressed_mtrl_005 = 2131165249;
			
			// aapt resource value: 0x7F070042
			public const int abc_scrubber_primary_mtrl_alpha = 2131165250;
			
			// aapt resource value: 0x7F070043
			public const int abc_scrubber_track_mtrl_alpha = 2131165251;
			
			// aapt resource value: 0x7F070044
			public const int abc_seekbar_thumb_material = 2131165252;
			
			// aapt resource value: 0x7F070045
			public const int abc_seekbar_tick_mark_material = 2131165253;
			
			// aapt resource value: 0x7F070046
			public const int abc_seekbar_track_material = 2131165254;
			
			// aapt resource value: 0x7F070047
			public const int abc_spinner_mtrl_am_alpha = 2131165255;
			
			// aapt resource value: 0x7F070048
			public const int abc_spinner_textfield_background_material = 2131165256;
			
			// aapt resource value: 0x7F070049
			public const int abc_switch_thumb_material = 2131165257;
			
			// aapt resource value: 0x7F07004A
			public const int abc_switch_track_mtrl_alpha = 2131165258;
			
			// aapt resource value: 0x7F07004B
			public const int abc_tab_indicator_material = 2131165259;
			
			// aapt resource value: 0x7F07004C
			public const int abc_tab_indicator_mtrl_alpha = 2131165260;
			
			// aapt resource value: 0x7F070054
			public const int abc_textfield_activated_mtrl_alpha = 2131165268;
			
			// aapt resource value: 0x7F070055
			public const int abc_textfield_default_mtrl_alpha = 2131165269;
			
			// aapt resource value: 0x7F070056
			public const int abc_textfield_search_activated_mtrl_alpha = 2131165270;
			
			// aapt resource value: 0x7F070057
			public const int abc_textfield_search_default_mtrl_alpha = 2131165271;
			
			// aapt resource value: 0x7F070058
			public const int abc_textfield_search_material = 2131165272;
			
			// aapt resource value: 0x7F07004D
			public const int abc_text_cursor_material = 2131165261;
			
			// aapt resource value: 0x7F07004E
			public const int abc_text_select_handle_left_mtrl_dark = 2131165262;
			
			// aapt resource value: 0x7F07004F
			public const int abc_text_select_handle_left_mtrl_light = 2131165263;
			
			// aapt resource value: 0x7F070050
			public const int abc_text_select_handle_middle_mtrl_dark = 2131165264;
			
			// aapt resource value: 0x7F070051
			public const int abc_text_select_handle_middle_mtrl_light = 2131165265;
			
			// aapt resource value: 0x7F070052
			public const int abc_text_select_handle_right_mtrl_dark = 2131165266;
			
			// aapt resource value: 0x7F070053
			public const int abc_text_select_handle_right_mtrl_light = 2131165267;
			
			// aapt resource value: 0x7F070059
			public const int abc_vector_test = 2131165273;
			
			// aapt resource value: 0x7F07005A
			public const int avd_hide_password = 2131165274;
			
			// aapt resource value: 0x7F07005B
			public const int avd_show_password = 2131165275;
			
			// aapt resource value: 0x7F07005C
			public const int design_bottom_navigation_item_background = 2131165276;
			
			// aapt resource value: 0x7F07005D
			public const int design_fab_background = 2131165277;
			
			// aapt resource value: 0x7F07005E
			public const int design_ic_visibility = 2131165278;
			
			// aapt resource value: 0x7F07005F
			public const int design_ic_visibility_off = 2131165279;
			
			// aapt resource value: 0x7F070060
			public const int design_password_eye = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int design_snackbar_background = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int ic_mtrl_chip_checked_black = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int ic_mtrl_chip_checked_circle = 2131165283;
			
			// aapt resource value: 0x7F070064
			public const int ic_mtrl_chip_close_circle = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int mtrl_snackbar_background = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int mtrl_tabs_default_indicator = 2131165286;
			
			// aapt resource value: 0x7F070067
			public const int navigation_empty_icon = 2131165287;
			
			// aapt resource value: 0x7F070068
			public const int notification_action_background = 2131165288;
			
			// aapt resource value: 0x7F070069
			public const int notification_bg = 2131165289;
			
			// aapt resource value: 0x7F07006A
			public const int notification_bg_low = 2131165290;
			
			// aapt resource value: 0x7F07006B
			public const int notification_bg_low_normal = 2131165291;
			
			// aapt resource value: 0x7F07006C
			public const int notification_bg_low_pressed = 2131165292;
			
			// aapt resource value: 0x7F07006D
			public const int notification_bg_normal = 2131165293;
			
			// aapt resource value: 0x7F07006E
			public const int notification_bg_normal_pressed = 2131165294;
			
			// aapt resource value: 0x7F07006F
			public const int notification_icon_background = 2131165295;
			
			// aapt resource value: 0x7F070070
			public const int notification_template_icon_bg = 2131165296;
			
			// aapt resource value: 0x7F070071
			public const int notification_template_icon_low_bg = 2131165297;
			
			// aapt resource value: 0x7F070072
			public const int notification_tile_bg = 2131165298;
			
			// aapt resource value: 0x7F070073
			public const int notify_panel_notification_icon_bg = 2131165299;
			
			// aapt resource value: 0x7F070074
			public const int tooltip_frame_dark = 2131165300;
			
			// aapt resource value: 0x7F070075
			public const int tooltip_frame_light = 2131165301;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int MainTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
